🐛 Fix "can't find referenced class" caused by desugaring
shreyashsaitwal/rush-cli pull request #58
Opened 2024-01-09 11:06 UTC by hammerhai

[REFERENCE 602](https://community.kodular.io/t/rush-a-new-and-improved-way-of-building-extensions/111470/602) within topic.

```java
// After `min_sdk` set to 24 or higher
import android.app.Application.ActivityLifecycleCallbacks;
```

```java
// Before `min_sdk` set to 24 or higher
import android.app.Application.ActivityLifecycleCallbacks;
import android.app.Application.ActivityLifecycleCallbacks..CC;
```

2024-01-09 18:52 UTC, shreyashsaitwal requested changes

2024-01-09 18:52 UTC, shreyashsaitwal commented on lib/src/commands/build/tools/executor.dart
> +      ...['--min-api', '${config.minSdk}'],
IDK if I remember it correctly but APK generation fails if an extension's DEX file is compiled with a higher min-api than that of AI2. Correct me if I'm wrong or if this has changed recently.

2024-01-09 18:54 UTC, hammerhai commented on lib/src/commands/build/tools/executor.dart
> +      ...['--min-api', '${config.minSdk}'],
I have compiled successfully using App Inventor, with a `min_sdk` of 24!

2024-01-11 06:29 UTC, shreyashsaitwal reviewed
Lgtm, thanks!

2024-01-11 06:30 UTC, shreyashsaitwal approved these changes
Lgtm, thanks!

2024-01-11 06:33 UTC, merged